// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smartDoor.proto

package com.smartdoor.smarthome;

public interface DoorStatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DoorStatus)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool openOnOff = 2;</code>
   */
  boolean getOpenOnOff();

  /**
   * <code>string statusMsg = 3;</code>
   */
  java.lang.String getStatusMsg();
  /**
   * <code>string statusMsg = 3;</code>
   */
  com.google.protobuf.ByteString
      getStatusMsgBytes();
}
