// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smartDoor.proto

package com.smartdoor.smarthome;

public interface LockStatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LockStatus)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool lockOnOff = 4;</code>
   */
  boolean getLockOnOff();

  /**
   * <code>string statusMsg = 5;</code>
   */
  java.lang.String getStatusMsg();
  /**
   * <code>string statusMsg = 5;</code>
   */
  com.google.protobuf.ByteString
      getStatusMsgBytes();
}
