// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smartDoor.proto

package com.smartdoor.smarthome;

public final class SmartDoorOuterClass {
  private SmartDoorOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DoorToggle_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DoorToggle_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LockToggle_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LockToggle_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017smartDoor.proto\"2\n\nDoorToggle\022\021\n\topenO" +
      "nOff\030\001 \001(\010\022\021\n\tstatusMsg\030\002 \001(\t\"2\n\nLockTog" +
      "gle\022\021\n\tlockOnOff\030\001 \001(\010\022\021\n\tstatusMsg\030\002 \001(" +
      "\t2\256\001\n\tSmartDoor\022&\n\010openDoor\022\013.DoorToggle" +
      "\032\013.DoorToggle\"\000\022\'\n\tcloseDoor\022\013.DoorToggl" +
      "e\032\013.DoorToggle\"\000\022&\n\010lockDoor\022\013.LockToggl" +
      "e\032\013.LockToggle\"\000\022(\n\nunlockDoor\022\013.LockTog" +
      "gle\032\013.LockToggle\"\000B\033\n\027com.smartdoor.smar" +
      "thomeP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_DoorToggle_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_DoorToggle_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DoorToggle_descriptor,
        new java.lang.String[] { "OpenOnOff", "StatusMsg", });
    internal_static_LockToggle_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_LockToggle_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LockToggle_descriptor,
        new java.lang.String[] { "LockOnOff", "StatusMsg", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
