// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smartPrinter.proto

package com.smartprinter.smarthome;

public interface PowerOnOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PowerOn)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool powerOnOff = 1;</code>
   */
  boolean getPowerOnOff();
}
