// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smartPrinter.proto

package com.smartprinter.smarthome;

public interface PrintReportOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PrintReport)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string report = 1;</code>
   */
  java.lang.String getReport();
  /**
   * <code>string report = 1;</code>
   */
  com.google.protobuf.ByteString
      getReportBytes();
}
