// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smartPrinter.proto

package com.smartprinter.smarthome;

public final class SmartPrinterOuterClass {
  private SmartPrinterOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PowerOn_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PowerOn_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PrintReport_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PrintReport_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022smartPrinter.proto\"\035\n\007PowerOn\022\022\n\npower" +
      "OnOff\030\001 \001(\010\"\035\n\013PrintReport\022\016\n\006report\030\001 \001" +
      "(\t2_\n\014SmartPrinter\022\036\n\006turnOn\022\010.PowerOn\032\010" +
      ".PowerOn\"\000\022/\n\013printReport\022\014.PrintReport\032" +
      "\014.PrintReport\"\000(\0010\001B\036\n\032com.smartprinter." +
      "smarthomeP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_PowerOn_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PowerOn_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PowerOn_descriptor,
        new java.lang.String[] { "PowerOnOff", });
    internal_static_PrintReport_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_PrintReport_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PrintReport_descriptor,
        new java.lang.String[] { "Report", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
