// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smartFire.proto

package com.smartfire.smarthome;

public interface FireStatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:FireStatus)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool lightsOnOff = 2;</code>
   */
  boolean getLightsOnOff();

  /**
   * <code>string statusMsg = 3;</code>
   */
  java.lang.String getStatusMsg();
  /**
   * <code>string statusMsg = 3;</code>
   */
  com.google.protobuf.ByteString
      getStatusMsgBytes();
}
