// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smartFire.proto

package com.smartfire.smarthome;

public final class SmartFireOuterClass {
  private SmartFireOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SwitchStatus_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SwitchStatus_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FireStatus_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FireStatus_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TempratureRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TempratureRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TempratureResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TempratureResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017smartFire.proto\"#\n\014SwitchStatus\022\023\n\013swi" +
      "tchOnOff\030\001 \001(\010\"!\n\nFireStatus\022\023\n\013lightsOn" +
      "Off\030\002 \001(\010\"\'\n\021TempratureRequest\022\022\n\ntempra" +
      "ture\030\003 \001(\005\"(\n\022TempratureResponse\022\022\n\ntemp" +
      "rature\030\003 \001(\0052\354\001\n\tSmartFire\022*\n\010switchOn\022\r" +
      ".SwitchStatus\032\r.SwitchStatus\"\000\022+\n\tswitch" +
      "Off\022\r.SwitchStatus\032\r.SwitchStatus\"\000\022$\n\006f" +
      "ireOn\022\013.FireStatus\032\013.FireStatus\"\000\022%\n\007fir" +
      "eOff\022\013.FireStatus\032\013.FireStatus\"\000\0229\n\ntemp" +
      "rature\022\022.TempratureRequest\032\023.TempratureR" +
      "esponse\"\0000\001B\033\n\027com.smartfire.smarthomeP\001" +
      "b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_SwitchStatus_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SwitchStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SwitchStatus_descriptor,
        new java.lang.String[] { "SwitchOnOff", });
    internal_static_FireStatus_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_FireStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FireStatus_descriptor,
        new java.lang.String[] { "LightsOnOff", });
    internal_static_TempratureRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_TempratureRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TempratureRequest_descriptor,
        new java.lang.String[] { "Temprature", });
    internal_static_TempratureResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_TempratureResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TempratureResponse_descriptor,
        new java.lang.String[] { "Temprature", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
