// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smartFire.proto

package com.smartfire.smarthome;

public interface SwitchStatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SwitchStatus)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool switchOnOff = 1;</code>
   */
  boolean getSwitchOnOff();
}
