// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smartFire.proto

package com.smartfire.smarthome;

public interface TempratureResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TempratureResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 temprature = 6;</code>
   */
  int getTemprature();

  /**
   * <code>string statusMsg = 7;</code>
   */
  java.lang.String getStatusMsg();
  /**
   * <code>string statusMsg = 7;</code>
   */
  com.google.protobuf.ByteString
      getStatusMsgBytes();
}
