// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smartFire.proto

package com.smartfire.smarthome;

public interface TempratureSettingOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TempratureSetting)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 temprature = 4;</code>
   */
  int getTemprature();

  /**
   * <code>string statusMsg = 5;</code>
   */
  java.lang.String getStatusMsg();
  /**
   * <code>string statusMsg = 5;</code>
   */
  com.google.protobuf.ByteString
      getStatusMsgBytes();
}
