// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smartLight.proto

package com.smartlight.smarthome;

public interface IntensitySettingOrBuilder extends
    // @@protoc_insertion_point(interface_extends:IntensitySetting)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 intensity = 4;</code>
   */
  int getIntensity();

  /**
   * <code>string statusMsg = 5;</code>
   */
  java.lang.String getStatusMsg();
  /**
   * <code>string statusMsg = 5;</code>
   */
  com.google.protobuf.ByteString
      getStatusMsgBytes();
}
