// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smartLight.proto

package com.smartlight.smarthome;

public interface IntensityResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:IntensityResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 intensity = 3;</code>
   */
  int getIntensity();
}
