// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smartLight.proto

package com.smartlight.smarthome;

public interface LightsStatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LightsStatus)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool lightsOnOff = 2;</code>
   */
  boolean getLightsOnOff();
}
