// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smartLight.proto

package com.smartlight.smarthome;

public final class SmartLightOuterClass {
  private SmartLightOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SwitchStatus_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SwitchStatus_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LightsStatus_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LightsStatus_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_IntensitySetting_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_IntensitySetting_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020smartLight.proto\"#\n\014SwitchStatus\022\023\n\013sw" +
      "itchOnOff\030\001 \001(\010\"6\n\014LightsStatus\022\023\n\013light" +
      "sOnOff\030\002 \001(\010\022\021\n\tstatusMsg\030\003 \001(\t\"8\n\020Inten" +
      "sitySetting\022\021\n\tintensity\030\004 \001(\005\022\021\n\tstatus" +
      "Msg\030\005 \001(\t2\265\002\n\nSmartLight\022*\n\010switchOn\022\r.S" +
      "witchStatus\032\r.SwitchStatus\"\000\022+\n\tswitchOf" +
      "f\022\r.SwitchStatus\032\r.SwitchStatus\"\000\022*\n\010lig" +
      "htsOn\022\r.LightsStatus\032\r.LightsStatus\"\000\022+\n" +
      "\tlightsOff\022\r.LightsStatus\032\r.LightsStatus" +
      "\"\000\022;\n\017brightintensity\022\021.IntensitySetting" +
      "\032\021.IntensitySetting\"\0000\001\0228\n\014dimintensity\022" +
      "\021.IntensitySetting\032\021.IntensitySetting\"\0000" +
      "\001B\034\n\030com.smartlight.smarthomeP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_SwitchStatus_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SwitchStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SwitchStatus_descriptor,
        new java.lang.String[] { "SwitchOnOff", });
    internal_static_LightsStatus_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_LightsStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LightsStatus_descriptor,
        new java.lang.String[] { "LightsOnOff", "StatusMsg", });
    internal_static_IntensitySetting_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_IntensitySetting_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_IntensitySetting_descriptor,
        new java.lang.String[] { "Intensity", "StatusMsg", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
