// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smartLight.proto

package com.smartlight.smarthome;

public final class SmartLight {
  private SmartLight() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SwitchStatus_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SwitchStatus_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LightsStatus_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LightsStatus_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_IntensityRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_IntensityRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_IntensityResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_IntensityResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020smartLight.proto\"#\n\014SwitchStatus\022\023\n\013sw" +
      "itchOnOff\030\001 \001(\010\"#\n\014LightsStatus\022\023\n\013light" +
      "sOnOff\030\002 \001(\010\"%\n\020IntensityRequest\022\021\n\tinte" +
      "nsity\030\003 \001(\005\"&\n\021IntensityResponse\022\021\n\tinte" +
      "nsity\030\003 \001(\0052\365\001\n\tSmartDoor\022*\n\010switchOn\022\r." +
      "SwitchStatus\032\r.SwitchStatus\"\000\022+\n\tswitchO" +
      "ff\022\r.SwitchStatus\032\r.SwitchStatus\"\000\022*\n\010li" +
      "ghtsOn\022\r.LightsStatus\032\r.LightsStatus\"\000\022+" +
      "\n\tlightsOff\022\r.LightsStatus\032\r.LightsStatu" +
      "s\"\000\0226\n\tintensity\022\021.IntensityRequest\032\022.In" +
      "tensityResponse\"\0000\001B\034\n\030com.smartlight.sm" +
      "arthomeP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_SwitchStatus_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SwitchStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SwitchStatus_descriptor,
        new java.lang.String[] { "SwitchOnOff", });
    internal_static_LightsStatus_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_LightsStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LightsStatus_descriptor,
        new java.lang.String[] { "LightsOnOff", });
    internal_static_IntensityRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_IntensityRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_IntensityRequest_descriptor,
        new java.lang.String[] { "Intensity", });
    internal_static_IntensityResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_IntensityResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_IntensityResponse_descriptor,
        new java.lang.String[] { "Intensity", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
